name: dockerbuildandpush

on:
  workflow_run:
     workflows: ["dotnetbuild"]
     types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write        
    
    steps:
    - uses: actions/checkout@v3
    - name: download build artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: serialrider
        path: build
    - name: build the docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
